import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';

test('browser production gates, real socket adapters, refresh and PDF', async ({ page, request }, info) => {
  const audit = async () => (await (await request.get('/synthetic-audit')).json()).requests;
  await page.goto('/');
  await page.getByLabel('你想研究什么？', { exact: true }).fill('What determines retrieval?');
  await page.getByLabel('执行模式', { exact: true }).selectOption('real');
  await page.getByRole('button', { name: '创建并查看计划', exact: true }).click();
  const generate = page.getByRole('button', { name: '授权并生成计划', exact: true });
  await expect(generate).toBeDisabled();
  expect(await audit()).toEqual([]);
  const total = page.getByRole('group', { name: '整个任务累计上限（包含规划）', exact: true });
  await total.getByLabel('金额上限 / 元').fill('1');
  await total.getByLabel('远程模型次数').fill('10');
  await total.getByLabel('本地模型次数').fill('10');
  await total.getByLabel('外部请求次数').fill('30');
  const planning = page.getByRole('group', { name: '规划阶段上限', exact: true });
  await planning.getByLabel('金额上限 / 元').fill('0.2');
  await planning.getByLabel('远程模型次数').fill('1');
  await page.getByRole('checkbox').check();
  await generate.click();
  const execute = page.getByRole('button', { name: '授权并执行此版本', exact: true });
  await expect(execute).toBeDisabled();
  expect((await audit()).length).toBe(1);
  await page.reload();
  await expect(execute).toBeDisabled();
  const execution = page.getByRole('group', { name: '本次执行阶段上限', exact: true });
  await execution.getByLabel('金额上限 / 元').fill('0.8');
  await execution.getByLabel('远程模型次数').fill('9');
  await execution.getByLabel('本地模型次数').fill('10');
  await execution.getByLabel('外部请求次数').fill('30');
  await page.getByRole('checkbox').check();
  await execute.click();
  await expect(page.locator('.task-heading')).toContainText('已完成', { timeout: 25000 });
  const calls = await audit();
  expect(calls.filter(([method, path]) => method === 'POST' && path === '/v1/chat/completions').length).toBe(5);
  expect(calls.filter(([method, path]) => method === 'POST' && path === '/api/v1/documents').length).toBe(3);
  await page.reload();
  await page.getByRole('button', { name: '研究报告', exact: true }).click();
  await expect(page.locator('.markdown')).toBeVisible();
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: 'PDF', exact: true }).click();
  const download = await downloadEvent;
  const target = info.outputPath('synthetic.pdf');
  await download.saveAs(target);
  expect((await readFile(target)).subarray(0, 5).toString()).toBe('%PDF-');
  expect(await audit()).toEqual(calls);
});
